### ISSUE TITLE
Luna Launcher FC

### ISSUE THREAD

**Issue by spezi77** [CypherOS/packages_apps_Luna#6]
--------- beginning of crash
01-05 16:04:42.625  3434  3434 E AndroidRuntime: FATAL EXCEPTION: main
01-05 16:04:42.625  3434  3434 E AndroidRuntime: Process: com.android.launcher3, PID: 3434
01-05 16:04:42.625  3434  3434 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.launcher3/com.android.launcher3.Launcher}: android.view.InflateException: Binary XML file line #62: Binary XML file line #16: Error inflating class co.aoscp.lovegood.qsb.AllAppsQsbView
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2915)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3050)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1810)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6685)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #62: Binary XML file line #16: Error inflating class co.aoscp.lovegood.qsb.AllAppsQsbView
01-05 16:04:42.625  3434  3434 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #16: Error inflating class co.aoscp.lovegood.qsb.AllAppsQsbView
01-05 16:04:42.625  3434  3434 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:965)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:995)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at com.android.launcher3.Launcher.onCreate(Launcher.java:293)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7144)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7135)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2895)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3050)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1810)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6685)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: Caused by: java.lang.ClassCastException: com.android.launcher3.Launcher cannot be cast to co.aoscp.lovegood.LunaLauncher
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at co.aoscp.lovegood.qsb.BaseQsbView.<init>(BaseQsbView.java:99)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at co.aoscp.lovegood.qsb.AllAppsQsbView.<init>(AllAppsQsbView.java:72)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	at co.aoscp.lovegood.qsb.AllAppsQsbView.<init>(AllAppsQsbView.java:68)
01-05 16:04:42.625  3434  3434 E AndroidRuntime: 	... 31 more

**Comment by Sirhc95** [comment]
Luna Launcher only works on CypherOS unless modified in source

**Comment by spezi77** [comment]
I know. I have modified package names and sources where necessary to make it work in my rom. Just to make sure, does the current branch work in CypherOS?

**Comment by Sirhc95** [comment]
Yes

**Comment by spezi77** [comment]
Ok, thank you sir for your prompt reply, and many thanks for your great work. This issue isn't an issue with CypherOS then.
